### ISSUE TITLE
.gitignore 파일 복사 안되는 버그 

### ISSUE THREAD

**Issue by jeonghwan-kim** [WePlanet/generator-weplajs#4]
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /Users/Chris/.nvm/versions/node/v6.9.1/lib/node_modules/generator-weplajs/generators/app/templates/.gitignore
    at EditionInterface.exports._copySingle (/Users/Chris/.nvm/versions/node/v6.9.1/lib/node_modules/generator-weplajs/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/Users/Chris/.nvm/versions/node/v6.9.1/lib/node_modules/generator-weplajs/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at child.writing (/Users/Chris/.nvm/versions/node/v6.9.1/lib/node_modules/generator-weplajs/generators/app/index.js:75:13)
    at Object.<anonymous> (/Users/Chris/.nvm/versions/node/v6.9.1/lib/node_modules/generator-weplajs/node_modules/yeoman-generator/lib/base.js:431:23)
    at /Users/Chris/.nvm/versions/node/v6.9.1/lib/node_modules/generator-weplajs/node_modules/run-async/index.js:26:25
    at /Users/Chris/.nvm/versions/node/v6.9.1/lib/node_modules/generator-weplajs/node_modules/run-async/index.js:25:19
    at /Users/Chris/.nvm/versions/node/v6.9.1/lib/node_modules/generator-weplajs/node_modules/yeoman-generator/lib/base.js:432:9
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**Comment by jeonghwan-kim** [comment]
https://github.com/facebookincubator/create-react-app/pull/79/commits/c0d34f3e7975ace7326920300aa329c3c8997126
